package com.ericsson.dao.entity;

// Generated 2015-10-10 13:46:24 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysMenu generated by hbm2java
 */
@Entity
@Table(name = "sys_menu", schema = "public")
public class SysMenu implements java.io.Serializable {

	private int id;
	private int pid;
	private String name;
	private String url;
	private int orderNum;
	private Integer type;
	private Date updateTime;
	private Date createTime;

	public SysMenu() {
	}

	public SysMenu(int id, int pid, String name, String url, int orderNum,
			Date updateTime, Date createTime) {
		this.id = id;
		this.pid = pid;
		this.name = name;
		this.url = url;
		this.orderNum = orderNum;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	public SysMenu(int id, int pid, String name, String url, int orderNum,
			Integer type, Date updateTime, Date createTime) {
		this.id = id;
		this.pid = pid;
		this.name = name;
		this.url = url;
		this.orderNum = orderNum;
		this.type = type;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	@Id
	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "PID", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "NAME", nullable = false, length = 1)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "URL", nullable = false, length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ORDER_NUM", nullable = false)
	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIME", nullable = false, length = 22)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 22)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
