package com.ericsson.dao.entity;

// Generated 2015-10-10 16:34:56 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test", schema = "public")
public class Test implements java.io.Serializable {

	private Integer id;
	private String name;

	public Test() {
	}

	public Test(int id) {
		this.id = id;
	}

	public Test(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@SequenceGenerator(name="\"test_ID_seq\"",sequenceName="\"test_ID_seq\"",allocationSize=1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="\"test_ID_seq\"")
	@Column(name = "ID")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
