package com.ericsson.dao.entity;

// Generated 2015-10-13 17:16:11 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysRole generated by hbm2java
 */
@Entity
@Table(name = "sys_role", schema = "public")
public class SysRole implements java.io.Serializable {

	private int id;
	private String name;
	private boolean isBuiltin;
	private Date updateTime;
	private Date createTime;

	public SysRole() {
	}

	public SysRole(int id, String name, boolean isBuiltin, Date updateTime,
			Date createTime) {
		this.id = id;
		this.name = name;
		this.isBuiltin = isBuiltin;
		this.updateTime = updateTime;
		this.createTime = createTime;
	}

	@Id
	@SequenceGenerator(name="geely_sequences", sequenceName="geely_sequences", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE,generator="geely_sequences")
	@Column(name = "\"ID\"", unique=true, nullable=false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "\"NAME\"", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "\"IS_BUILTIN\"", nullable = false)
	public boolean isIsBuiltin() {
		return this.isBuiltin;
	}

	public void setIsBuiltin(boolean isBuiltin) {
		this.isBuiltin = isBuiltin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"UPDATE_TIME\"", nullable = false, length = 22)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "\"CREATE_TIME\"", nullable = false, length = 22)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
